# Generated by Django 4.0.5 on 2022-07-04 22:23

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_video_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
