# Generated by Django 4.0.5 on 2022-07-04 22:35

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_post_url_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
