# Generated by Django 4.0.5 on 2022-07-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0007_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Java', max_length=50),
        ),
    ]
