# Generated by Django 4.0.5 on 2022-07-05 13:47

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0008_category_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
